#!/usr/bin/env python3
"""Render factual execution reports from immutable manifests and run logs."""
from __future__ import annotations
import csv,json,hashlib,statistics,math
from collections import Counter
from pathlib import Path
ROOT=Path('/home/yanbo/net_vlm_person_fallen_v2_optimization');DATA=ROOT/'01_data';REPORT=ROOT/'reports';RUN=ROOT/'02_p0_image_baseline/runs/P0_20260826_191155';DS=Path('/home/yanbo/net_vlm_xunjian_dataset')
def load(p):
 with p.open(encoding='utf-8',newline='') as f:return list(csv.DictReader(f))
def h(p):
 x=hashlib.sha256();x.update(p.read_bytes());return x.hexdigest()
def pct(xs,q):
 xs=sorted(xs);k=(len(xs)-1)*q;lo=math.floor(k);hi=math.ceil(k);return xs[lo] if lo==hi else xs[lo]+(xs[hi]-xs[lo])*(k-lo)
def main():
 REPORT.mkdir(exist_ok=True)
 build=json.loads((DATA/'build_summary.json').read_text()); val=json.loads((DATA/'post_ingest_validator.json').read_text()); frozen=load(DATA/'frozen_manifest.csv');logs=load(RUN/'request_log.csv');pred=load(RUN/'predictions.csv'); media=load(DS/'01_annotations/media.csv');labels=load(DS/'01_annotations/labels.csv')
 spl=Counter(r['split'] for r in frozen);roles=Counter(r['sample_role'] for r in frozen);groups=len(set(r['group_id'] for r in frozen)); lats=[float(r['latency_seconds']) for r in logs]
 protocol_errors=Counter(r['error_type'] for r in pred); raw_sample=json.loads(next((RUN/'raw_responses.jsonl').open()))['response'];outer=json.loads(raw_sample)
 source=f'''# 01 Source and GT audit\n\n## Confirmed facts\n\n- Source: `/home/yanbo/下载/batches/batch_person-fallen-v2-camera1p5m`; images={build['image_count']}, prompts={build['prompt_count']}; one-to-one mapping status **PASS**.\n- All images passed Pillow integrity checks. Exact duplicate files=0; dHash near-duplicate candidate groups=0.\n- Prompt-derived GT counts: positive=200, negative=100, hard_negative=180, uncertain=20, across 50 prompt/scenario groups.\n- GT basis for every row: `user_confirmed_prompt_image_alignment`. It is not independent human visual review and no VLM created GT.\n- Generation manifest identifies provider `ebondai`, model/version `gpt-image-2`, batch `batch_person-fallen-v2-camera1p5m`, generation date 2026-08-26 and simulated camera height about 1.5m. Seed was unavailable for all 500 items (`unknown`); metadata completeness is false if seed is required, otherwise documented source metadata fields are present.\n\n## Reasoned interpretation\n\nPrompt declarations and full scene semantics are sufficient for the user-authorized prompt-derived GT, but not for a claim of independent visual review.\n\n## Unverified\n\nReal camera/robot/production generalization is not measured by this AIGC batch.\n'''
 ingest=f'''# 02 Ingest report\n\n## Confirmed facts\n\n- Pre-ingest validator: `valid`, errors=0, full hash check=true, warnings=387; pre counts media=3701, labels=3701, batches=40, splits=2058.\n- All 50 group-level media dry-runs passed (500 planned new media; no duplicate reuse). Official `ingest_media.py add` completed 50 transactions, adding 500 media; official `add-label` completed 500 prompt-derived V2 labels (all review status `unreviewed`).\n- Post-ingest: media=4201, labels=4201, batches=41, splits=2058. New person_fallen media=500 and labels=500; roles={dict(roles)}; version set={{v2.0}}. Other event label counts remained: dangerous_weapon_present=199, evacuation_indicator_light_noncompliant=187, fire_equipment_noncompliant=1288, garbage_present=184, open_flame_present=1186, person_smoking=164, water_accumulation=493.\n- Formal validator after ingest: status={val['status']}, error_count={val['error_count']}, warning_count={val['warning_count']}, full_hash_check={val['full_hash_check']}.\n- `rebuild_review_links.py` completed with conflict_count=0 and error_count=0; it created 1386 missing review links (including historical links that the tool found missing).\n\n## Boundary\n\nNo shared annotation CSV was manually edited or wholesale-overwritten.\n'''
 split=f'''# 03 Split freeze report\n\n## Confirmed facts\n\n- `frozen_splits.csv` and `frozen_manifest.csv` each contain 500 formal media rows.\n- Group-disjoint split counts: DEV={spl['DEV']}, VAL={spl['VAL']}, HOLDOUT={spl['HOLDOUT']}; groups={groups}; cross-split groups=0.\n- All uncertain rows are in DEV qualitative pool; no uncertain row is in HOLDOUT. Determinate rows: DEV=290, VAL=100, HOLDOUT=90.\n- `frozen_splits.csv` SHA-256: `{h(DATA/'frozen_splits.csv')}`. `frozen_manifest.csv` SHA-256: `{h(DATA/'frozen_manifest.csv')}`.\n- The current production tool set has no safe split-writing subcommand. Therefore `FORMAL_SPLITS_CSV_UPDATED=false`; `LOCAL_FROZEN_SPLIT_MANIFEST=true` is the P0 source of truth. `03_splits/splits.csv`/shared `splits.csv` was not hand-edited.\n\n## Holdout boundary\n\nHOLDOUT is sealed for this P0: model requests=0 and consumed=false.\n'''
 p0=f'''# 04 P0 baseline report\n\n## Execution status\n\n`P0_IMAGE_BASELINE_V2` executed all planned DEV/VAL requests (DEV=310, VAL=100, HOLDOUT=0) against `http://192.168.20.62:11434`, model `qwen3.5:4b`, single concurrency, letterbox 448x336, JPEG quality 70. P0 prompt SHA-256 is `b457a2442b8c4cca66866ecd7fcaaa765524740f1019e7811a05ec8e2c8335f4`.\n\n## Confirmed protocol outcome\n\n- HTTP success=100% (410/410); first-attempt success=100%.\n- JSON parse success=0% (0/410); schema success=0% (0/410); canonical prediction success=0% (0/410).\n- Every failure has the same evidence: the Ollama outer JSON placed the requested object in `thinking`, while `response` was an empty string. The strict P0 parser accepts only the required JSON object in `response`; it did not extract or backfill reasoning text.\n- Thus every request is a protocol failure, not a negative prediction. Classification metrics TP/FP/TN/FN and Precision/Recall/F1/Accuracy/FPR are **not available**. `hard_negative_fpr` and model uncertain rate are likewise not available.\n- Measured transport response latency across all HTTP-successful requests: cold={lats[0]:.6f}s, post-cold mean={statistics.mean(lats[1:]):.6f}s, P50={pct(lats[1:],.5):.6f}s, P95={pct(lats[1:],.95):.6f}s, max={max(lats[1:]):.6f}s. These are protocol-failed transport observations, not a valid P0 classification-latency baseline.\n- `HOLDOUT_REQUESTS=0`; `HOLDOUT_CONSUMED=false`.\n\n## Quality gate\n\nThe required JSON/schema rate of 1.0 was not met. P0 is recorded as `COMPLETE_PROTOCOL_FAILURE`; no prompt/config change or rerun occurred in this P0.\n\n## Recommended next stage\n\nA separately versioned P1 protocol investigation may test a documented reasoning-disable/response-channel control (for example an Ollama-compatible `think=false` request only after verifying server support) and must use DEV only for development before any new frozen evaluation.\n'''
 final=f'''# Final execution report\n\n```text\nPROJECT=net_vlm\nEVENT=person_fallen\nEVENT_VERSION=v2.0\nSOURCE_MAPPING_STATUS=PASS\nGT_BUILD_STATUS=COMPLETE\nDATASET_INGEST_STATUS=COMPLETE\nDATASET_VALIDATION_STATUS=valid\nSPLIT_FREEZE_STATUS=COMPLETE\nFORMAL_SPLITS_CSV_UPDATED=false\nLOCAL_FROZEN_SPLIT_MANIFEST=true\nHOLDOUT_CONSUMED=false\nHOLDOUT_REQUESTS=0\nP0_NAME=P0_IMAGE_BASELINE_V2\nP0_STATUS=COMPLETE_PROTOCOL_FAILURE\nP0_MODEL=qwen3.5:4b\nP0_ENDPOINT=http://192.168.20.62:11434\nP0_PRIMARY_SOURCE=ai_generated\nP1_EXECUTED=false\nPRODUCTION_CODE_MODIFIED=false\nROBOT_CHAIN_STARTED=false\nSSH_OLLAMA_TUNNEL_USED=false\n```\n\n## Confirmed facts\n\n- Images/prompts: 500/500; mapping PASS; exact duplicates=0; dHash near-duplicate candidate groups=0.\n- Roles: positive=200, negative=100, hard_negative=180, uncertain=20.\n- Formal additions: media=500, labels=500; media IDs `IMG_003702` through `IMG_004201`; validator valid with 0 errors and full hash check.\n- Frozen split: DEV=310, VAL=100, HOLDOUT=90; HOLDOUT is unconsumed.\n- P0 executed 410 calls with HTTP 100%, but JSON/schema 0% because all model JSON appeared in `thinking` instead of empty `response`; no valid classification metric exists.\n\n## Reasoned conclusion\n\nThe data ingestion and split freeze are complete, but the P0 model-output contract failed. The next technically justified step is a separately versioned DEV-only protocol-control study, not accuracy tuning, higher resolution, crop/ROI, or holdout use.\n\n## Unverified\n\nNo conclusion about robot real-camera accuracy, production safety-inspection accuracy, or real-world generalization follows from this AIGC-only dataset or failed protocol run.\n'''
 (REPORT/'01_source_and_gt_audit.md').write_text(source);(REPORT/'02_ingest_report.md').write_text(ingest);(REPORT/'03_split_freeze_report.md').write_text(split);(REPORT/'04_p0_baseline_report.md').write_text(p0);(REPORT/'final_execution_report.md').write_text(final)
 mainmd=f'''# person_fallen V2.0 — formal intake and P0 record\n\n## Definition\n\nVisible-state image event: real person clearly lying/prone/supine/side-lying/horizontally collapsed on ground or other clearly abnormal non-rest support is positive. Intentional ground lying is positive. Transition/cause/injury/consciousness is not required.\n\n## Data and provenance\n\nAIGC source batch: `batch_person-fallen-v2-camera1p5m`; 500 gpt-image-2 images with user-confirmed prompt/image alignment. GT is prompt-derived, never VLM-generated and not independent visual review. Counts: positive 200; negative 100; hard-negative 180; uncertain 20. Metadata has no provider seed (500 unknown).\n\n## Formal dataset and freeze\n\nFormal media IDs: `IMG_003702`–`IMG_004201` (500 media/500 labels, V2.0). Split counts: DEV 310 / VAL 100 / HOLDOUT 90; group-disjoint across 50 groups. `frozen_splits.csv` SHA-256 `{h(DATA/'frozen_splits.csv')}`; P0 prompt SHA-256 `b457a2442b8c4cca66866ecd7fcaaa765524740f1019e7811a05ec8e2c8335f4`. `FORMAL_SPLITS_CSV_UPDATED=false`; local frozen manifest is P0 source of truth.\n\n## P0 outcome\n\nP0 used `qwen3.5:4b`, direct LAN `192.168.20.62:11434`, full image letterbox to 448×336 JPEG q70 and concurrency 1. DEV+VAL requests=410; HOLDOUT=0 and unconsumed. HTTP=100%, but JSON/schema=0% because the server placed output in `thinking` while required `response` was empty. This is `COMPLETE_PROTOCOL_FAILURE`, so TP/FP/TN/FN and classification metrics are unavailable.\n\n## Limitations and next stage\n\nThis is AIGC-only and does not establish robot or production accuracy. The next recommended work is a separately authorized DEV-only P1 output-channel protocol check; do not consume HOLDOUT or run P2/production integration.\n'''
 (ROOT/'PERSON_FALLEN_V2.md').write_text(mainmd)
 print('REPORTS_RENDERED')
if __name__=='__main__':main()
